
- name: assert all vars are set
  assert: { that: "{{ item }} != '' " }
  with_items:
  - service_name
  - installation_root_folder
  - temp_folder

- name: stop the old service
  win_nssm:
    name: "{{ service_name }}"
    state: absent
  become: yes

- name: remove temp folder
  win_file:
    path: "{{ temp_folder }}"
    state: absent
  when: clear_temp_folder | default('no') | bool

- name: remove tracking files
  win_file: 
    path: "{{ installation_root_folder }}\\{{ item }}"
    state: absent
  with_items:
    - "{{ app_name }}-previous"
    - "{{ app_name }}-current"

- name: find app versions
  win_find:
    paths: "{{ installation_root_folder }}"
    file_type: directory
  register: application_versions

- name: remove application versions
  win_file:
    path: "{{ item.path }}"
    state: absent
  with_items: "{{ application_versions.files }}"
  when: 
    - item.path | win_basename | regex_search("{{ app_name }}-")
