
- name: assert all vars are set
  assert: { that: "{{ item }} != '' " }
  with_items:
  - service_name
  - installation_root_folder
  - temp_folder

- name: stop the old service
  win_nssm:
    name: "{{ service_name }}"
    state: absent
  become: yes

- name: remove temp folder
  win_file:
    path: "{{ temp_folder }}"
    state: absent
  when: clear_temp_folder | default('no') | bool

- name: remove tracking files
  win_file: 
    path: "{{ installation_root_folder }}\\{{ item }}"
    state: absent
  with_items:
    - "{{ app_name }}-previous"
    - "{{ app_name }}-current"

- name: find app versions
  win_shell: |
    Get-ChildItem -Path {{ installation_root_folder }}\{{ app_name }}-* -Directory -Name
  register: application_versions
  changed_when: no

- name: remove application versions
  win_file:
    path: "{{ installation_root_folder }}\\{{ item }}"
    state: absent
  with_items: "{{ application_versions.stdout_lines }}"
  when: 
    - item | regex_search("{{ app_name }}-")
