
- name: start the service
  command: "launchctl load {{ service_plist_file_path }}"
  become: yes

- name: wait for service to start
  health_check:
    url: "http://localhost:{{ health_check_port | default(server_port) }}{{ health_check_uri | default('/manage/info') }}"
    expected_status: "{{ health_check_status | default('200') }}"
    max_retries: "{{ health_check_max_retries | default('20') }}"
